# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:35:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class AuditRefs(BaseModel):
    acronym: Optional[str] = Field(
        None, description='The conventional acronym for the audit/metric.'
    )
    group: Optional[str] = Field(
        None, description='The category group that the audit belongs to (optional).'
    )
    id: Optional[str] = Field(None, description='The audit ref id.')
    relevantAudits: Optional[List[str]] = Field(
        None, description='Any audit IDs closely relevant to this one.'
    )
    weight: Optional[float] = Field(
        None,
        description="The weight this audit's score has on the overall category score.",
    )


class Bucket(BaseModel):
    max: Optional[int] = Field(None, description="Upper bound for a bucket's range.")
    min: Optional[int] = Field(None, description="Lower bound for a bucket's range.")
    proportion: Optional[float] = Field(
        None, description='The proportion of data in this bucket.'
    )


class CategoryGroupV5(BaseModel):
    description: Optional[str] = Field(
        None, description='The description of what the category is grouping'
    )
    title: Optional[str] = Field(
        None, description='The human readable title of the group'
    )


class ConfigSettings(BaseModel):
    channel: Optional[str] = Field(
        None,
        description='How Lighthouse was run, e.g. from the Chrome extension or from the npm module.',
    )
    emulatedFormFactor: Optional[str] = Field(
        None,
        description='The form factor the emulation should use. This field is deprecated, form_factor should be used instead.',
    )
    formFactor: Optional[str] = Field(
        None,
        description='How Lighthouse should interpret this run in regards to scoring performance metrics and skipping mobile-only tests in desktop.',
    )
    locale: Optional[str] = Field(None, description='The locale setting.')
    onlyCategories: Optional[Any] = Field(
        None, description='List of categories of audits the run should conduct.'
    )


class Environment(BaseModel):
    benchmarkIndex: Optional[float] = Field(
        None,
        description='The benchmark index number that indicates rough device class.',
    )
    credits: Optional[Dict[str, str]] = Field(
        None,
        description='The version of libraries with which these results were generated. Ex: axe-core.',
    )
    hostUserAgent: Optional[str] = Field(
        None, description='The user agent string of the version of Chrome used.'
    )
    networkUserAgent: Optional[str] = Field(
        None, description='The user agent string that was sent over the network.'
    )


class LhrEntity(BaseModel):
    category: Optional[str] = Field(
        None, description='Optional. An optional category name for the entity.'
    )
    homepage: Optional[str] = Field(
        None, description='Optional. An optional homepage URL of the entity.'
    )
    isFirstParty: Optional[bool] = Field(
        None,
        description='Optional. An optional flag indicating if the entity is the first party.',
    )
    isUnrecognized: Optional[bool] = Field(
        None,
        description='Optional. An optional flag indicating if the entity is not recognized.',
    )
    name: Optional[str] = Field(None, description='Required. Name of the entity.')
    origins: Optional[List[str]] = Field(
        None,
        description='Required. A list of URL origin strings that belong to this entity.',
    )


class LighthouseAuditResultV5(BaseModel):
    description: Optional[str] = Field(
        None, description='The description of the audit.'
    )
    details: Optional[Dict[str, Any]] = Field(
        None, description='Freeform details section of the audit.'
    )
    displayValue: Optional[str] = Field(
        None, description='The value that should be displayed on the UI for this audit.'
    )
    errorMessage: Optional[str] = Field(
        None, description='An error message from a thrown error inside the audit.'
    )
    explanation: Optional[str] = Field(
        None, description='An explanation of the errors in the audit.'
    )
    id: Optional[str] = Field(None, description="The audit's id.")
    numericUnit: Optional[str] = Field(
        None,
        description='The unit of the numeric_value field. Used to format the numeric value for display.',
    )
    numericValue: Optional[float] = Field(
        None,
        description='A numeric value that has a meaning specific to the audit, e.g. the number of nodes in the DOM or the timestamp of a specific load event. More information can be found in the audit details, if present.',
    )
    score: Optional[Any] = Field(
        None, description='The score of the audit, can be null.'
    )
    scoreDisplayMode: Optional[str] = Field(
        None, description='The enumerated score display mode.'
    )
    title: Optional[str] = Field(None, description='The human readable title.')
    warnings: Optional[Any] = Field(
        None, description='Possible warnings that occurred in the audit, can be null.'
    )


class LighthouseCategoryV5(BaseModel):
    auditRefs: Optional[List[AuditRefs]] = Field(
        None,
        description='An array of references to all the audit members of this category.',
    )
    description: Optional[str] = Field(
        None,
        description='A more detailed description of the category and its importance.',
    )
    id: Optional[str] = Field(
        None, description='The string identifier of the category.'
    )
    manualDescription: Optional[str] = Field(
        None, description='A description for the manual audits in the category.'
    )
    score: Optional[Any] = Field(
        None,
        description="The overall score of the category, the weighted average of all its audits. (The category's score, can be null.)",
    )
    title: Optional[str] = Field(
        None, description='The human-friendly name of the category.'
    )


class PagespeedVersion(BaseModel):
    major: Optional[str] = Field(
        None,
        description='The major version number of PageSpeed used to generate these results.',
    )
    minor: Optional[str] = Field(
        None,
        description='The minor version number of PageSpeed used to generate these results.',
    )


class RendererFormattedStrings(BaseModel):
    auditGroupExpandTooltip: Optional[str] = Field(
        None, description='The tooltip text on an expandable chevron icon.'
    )
    calculatorLink: Optional[str] = Field(
        None,
        description='Text link pointing to the Lighthouse scoring calculator. This link immediately follows a sentence stating the performance score is calculated from the perf metrics.',
    )
    crcInitialNavigation: Optional[str] = Field(
        None,
        description='The label for the initial request in a critical request chain.',
    )
    crcLongestDurationLabel: Optional[str] = Field(
        None,
        description='The label for values shown in the summary of critical request chains.',
    )
    dropdownCopyJSON: Optional[str] = Field(
        None,
        description='Option in a dropdown menu that copies the Lighthouse JSON object to the system clipboard.',
    )
    dropdownDarkTheme: Optional[str] = Field(
        None,
        description='Option in a dropdown menu that toggles the themeing of the report between Light(default) and Dark themes.',
    )
    dropdownPrintExpanded: Optional[str] = Field(
        None,
        description='Option in a dropdown menu that opens a full Lighthouse report in a print dialog.',
    )
    dropdownPrintSummary: Optional[str] = Field(
        None,
        description='Option in a dropdown menu that opens a small, summary report in a print dialog.',
    )
    dropdownSaveGist: Optional[str] = Field(
        None,
        description='Option in a dropdown menu that saves the current report as a new GitHub Gist.',
    )
    dropdownSaveHTML: Optional[str] = Field(
        None,
        description="Option in a dropdown menu that saves the Lighthouse report HTML locally to the system as a '.html' file.",
    )
    dropdownSaveJSON: Optional[str] = Field(
        None,
        description="Option in a dropdown menu that saves the Lighthouse JSON object to the local system as a '.json' file.",
    )
    dropdownViewer: Optional[str] = Field(
        None,
        description='Option in a dropdown menu that opens the current report in the Lighthouse Viewer Application.',
    )
    errorLabel: Optional[str] = Field(
        None,
        description='The label shown next to an audit or metric that has had an error.',
    )
    errorMissingAuditInfo: Optional[str] = Field(
        None, description='The error string shown next to an erroring audit.'
    )
    footerIssue: Optional[str] = Field(
        None,
        description='Label for button to create an issue against the Lighthouse GitHub project.',
    )
    labDataTitle: Optional[str] = Field(
        None, description='The title of the lab data performance category.'
    )
    lsPerformanceCategoryDescription: Optional[str] = Field(
        None,
        description='The disclaimer shown under performance explaining that the network can vary.',
    )
    manualAuditsGroupTitle: Optional[str] = Field(
        None,
        description='The heading shown above a list of audits that were not computerd in the run.',
    )
    notApplicableAuditsGroupTitle: Optional[str] = Field(
        None,
        description='The heading shown above a list of audits that do not apply to a page.',
    )
    opportunityResourceColumnLabel: Optional[str] = Field(
        None,
        description='The heading for the estimated page load savings opportunity of an audit.',
    )
    opportunitySavingsColumnLabel: Optional[str] = Field(
        None,
        description='The heading for the estimated page load savings of opportunity audits.',
    )
    passedAuditsGroupTitle: Optional[str] = Field(
        None,
        description='The heading that is shown above a list of audits that are passing.',
    )
    runtimeDesktopEmulation: Optional[str] = Field(
        None,
        description='Descriptive explanation for emulation setting when emulating a generic desktop form factor, as opposed to a mobile-device like form factor.',
    )
    runtimeMobileEmulation: Optional[str] = Field(
        None,
        description='Descriptive explanation for emulation setting when emulating a Nexus 5X mobile device.',
    )
    runtimeNoEmulation: Optional[str] = Field(
        None,
        description='Descriptive explanation for emulation setting when no device emulation is set.',
    )
    runtimeSettingsAxeVersion: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows the version of the Axe library used',
    )
    runtimeSettingsBenchmark: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows the estimated CPU power of the machine running Lighthouse. Example row values: 532, 1492, 783.',
    )
    runtimeSettingsCPUThrottling: Optional[str] = Field(
        None,
        description='Label for a row in a table that describes the CPU throttling conditions that were used during a Lighthouse run, if any.',
    )
    runtimeSettingsChannel: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows in what tool Lighthouse is being run (e.g. The lighthouse CLI, Chrome DevTools, Lightrider, WebPageTest, etc).',
    )
    runtimeSettingsDevice: Optional[str] = Field(
        None,
        description="Label for a row in a table that describes the kind of device that was emulated for the Lighthouse run. Example values for row elements: 'No Emulation', 'Emulated Desktop', etc.",
    )
    runtimeSettingsFetchTime: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows the time at which a Lighthouse run was conducted; formatted as a timestamp, e.g. Jan 1, 1970 12:00 AM UTC.',
    )
    runtimeSettingsNetworkThrottling: Optional[str] = Field(
        None,
        description='Label for a row in a table that describes the network throttling conditions that were used during a Lighthouse run, if any.',
    )
    runtimeSettingsTitle: Optional[str] = Field(
        None,
        description='Title of the Runtime settings table in a Lighthouse report. Runtime settings are the environment configurations that a specific report used at auditing time.',
    )
    runtimeSettingsUA: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows the User Agent that was detected on the Host machine that ran Lighthouse.',
    )
    runtimeSettingsUANetwork: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows the User Agent that was used to send out all network requests during the Lighthouse run.',
    )
    runtimeSettingsUrl: Optional[str] = Field(
        None,
        description='Label for a row in a table that shows the URL that was audited during a Lighthouse run.',
    )
    runtimeUnknown: Optional[str] = Field(
        None,
        description='Descriptive explanation for a runtime setting that is set to an unknown value.',
    )
    scorescaleLabel: Optional[str] = Field(
        None,
        description='The label that explains the score gauges scale (0-49, 50-89, 90-100).',
    )
    showRelevantAudits: Optional[str] = Field(
        None,
        description='Label preceding a radio control for filtering the list of audits. The radio choices are various performance metrics (FCP, LCP, TBT), and if chosen, the audits in the report are hidden if they are not relevant to the selected metric.',
    )
    snippetCollapseButtonLabel: Optional[str] = Field(
        None,
        description='The label for the button to show only a few lines of a snippet',
    )
    snippetExpandButtonLabel: Optional[str] = Field(
        None, description='The label for the button to show all lines of a snippet'
    )
    thirdPartyResourcesLabel: Optional[str] = Field(
        None, description='This label is for a filter checkbox above a table of items'
    )
    throttlingProvided: Optional[str] = Field(
        None,
        description='Descriptive explanation for environment throttling that was provided by the runtime environment instead of provided by Lighthouse throttling.',
    )
    toplevelWarningsMessage: Optional[str] = Field(
        None,
        description='The label shown preceding important warnings that may have invalidated an entire report.',
    )
    varianceDisclaimer: Optional[str] = Field(
        None, description='The disclaimer shown below a performance metric value.'
    )
    viewTreemapLabel: Optional[str] = Field(
        None, description='Label for a button that opens the Treemap App'
    )
    warningAuditsGroupTitle: Optional[str] = Field(
        None,
        description='The heading that is shown above a list of audits that have warnings',
    )
    warningHeader: Optional[str] = Field(
        None, description='The label shown above a bulleted list of warnings.'
    )


class RuntimeError(BaseModel):
    code: Optional[str] = Field(
        None, description='The enumerated Lighthouse Error code.'
    )
    message: Optional[str] = Field(
        None, description='A human readable message explaining the error code.'
    )


class StackPack(BaseModel):
    descriptions: Optional[Dict[str, str]] = Field(
        None, description='The stack pack advice strings.'
    )
    iconDataURL: Optional[str] = Field(
        None, description='The stack pack icon data uri.'
    )
    id: Optional[str] = Field(None, description='The stack pack id.')
    title: Optional[str] = Field(None, description='The stack pack title.')


class Timing(BaseModel):
    total: Optional[float] = Field(
        None, description="The total duration of Lighthouse's run."
    )


class UserPageLoadMetricV5(BaseModel):
    category: Optional[str] = Field(
        None, description='The category of the specific time metric.'
    )
    distributions: Optional[List[Bucket]] = Field(
        None, description='Metric distributions. Proportions should sum up to 1.'
    )
    formFactor: Optional[str] = Field(
        None, description='Identifies the form factor of the metric being collected.'
    )
    median: Optional[int] = Field(
        None, description='The median number of the metric, in millisecond.'
    )
    metricId: Optional[str] = Field(
        None, description='Identifies the type of the metric.'
    )
    percentile: Optional[int] = Field(
        None,
        description='We use this field to store certain percentile value for this metric. For v4, this field contains pc50. For v5, this field contains pc90.',
    )


class CategoryEnum(Enum):
    CATEGORY_UNSPECIFIED = 'CATEGORY_UNSPECIFIED'
    ACCESSIBILITY = 'ACCESSIBILITY'
    BEST_PRACTICES = 'BEST_PRACTICES'
    PERFORMANCE = 'PERFORMANCE'
    PWA = 'PWA'
    SEO = 'SEO'


class Strategy(Enum):
    STRATEGY_UNSPECIFIED = 'STRATEGY_UNSPECIFIED'
    DESKTOP = 'DESKTOP'
    MOBILE = 'MOBILE'


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Category(RootModel[List[CategoryEnum]]):
    root: List[CategoryEnum]


class Categories(BaseModel):
    accessibility: Optional[LighthouseCategoryV5] = Field(
        None,
        description='The accessibility category, containing all accessibility related audits.',
    )
    best_practices: Optional[LighthouseCategoryV5] = Field(
        None,
        alias='best-practices',
        description='The best practices category, containing all best practices related audits.',
    )
    performance: Optional[LighthouseCategoryV5] = Field(
        None,
        description='The performance category, containing all performance related audits.',
    )
    pwa: Optional[LighthouseCategoryV5] = Field(
        None,
        description='The Progressive-Web-App (PWA) category, containing all pwa related audits.',
    )
    seo: Optional[LighthouseCategoryV5] = Field(
        None,
        description='The Search-Engine-Optimization (SEO) category, containing all seo related audits.',
    )


class I18n(BaseModel):
    rendererFormattedStrings: Optional[RendererFormattedStrings] = Field(
        None,
        description='Internationalized strings that are formatted to the locale in configSettings.',
    )


class LighthouseResultV5(BaseModel):
    audits: Optional[Dict[str, LighthouseAuditResultV5]] = Field(
        None, description='Map of audits in the LHR.'
    )
    categories: Optional[Categories] = Field(
        None, description='Map of categories in the LHR.'
    )
    categoryGroups: Optional[Dict[str, CategoryGroupV5]] = Field(
        None, description='Map of category groups in the LHR.'
    )
    configSettings: Optional[ConfigSettings] = Field(
        None, description='The configuration settings for this LHR.'
    )
    entities: Optional[List[LhrEntity]] = Field(
        None, description='Entity classification data.'
    )
    environment: Optional[Environment] = Field(
        None, description='Environment settings that were used when making this LHR.'
    )
    fetchTime: Optional[str] = Field(
        None, description='The time that this run was fetched.'
    )
    finalDisplayedUrl: Optional[str] = Field(
        None, description='URL displayed on the page after Lighthouse finishes.'
    )
    finalUrl: Optional[str] = Field(
        None, description='The final resolved url that was audited.'
    )
    fullPageScreenshot: Optional[Any] = Field(
        None,
        description='Screenshot data of the full page, along with node rects relevant to the audit results.',
    )
    i18n: Optional[I18n] = Field(
        None,
        description='The internationalization strings that are required to render the LHR.',
    )
    lighthouseVersion: Optional[str] = Field(
        None, description='The lighthouse version that was used to generate this LHR.'
    )
    mainDocumentUrl: Optional[str] = Field(
        None, description='URL of the main document request of the final navigation.'
    )
    requestedUrl: Optional[str] = Field(None, description='The original requested url.')
    runWarnings: Optional[List] = Field(
        None,
        description='List of all run warnings in the LHR. Will always output to at least `[]`.',
    )
    runtimeError: Optional[RuntimeError] = Field(
        None,
        description='A top-level error message that, if present, indicates a serious enough problem that this Lighthouse result may need to be discarded.',
    )
    stackPacks: Optional[List[StackPack]] = Field(
        None, description='The Stack Pack advice strings.'
    )
    timing: Optional[Timing] = Field(
        None, description='Timing information for this LHR.'
    )
    userAgent: Optional[str] = Field(
        None, description='The user agent that was used to run this LHR.'
    )


class PagespeedApiLoadingExperienceV5(BaseModel):
    id: Optional[str] = Field(
        None, description='The url, pattern or origin which the metrics are on.'
    )
    initial_url: Optional[str] = Field(
        None, description='The requested URL, which may differ from the resolved "id".'
    )
    metrics: Optional[Dict[str, UserPageLoadMetricV5]] = Field(
        None, description='The map of .'
    )
    origin_fallback: Optional[bool] = Field(
        None,
        description='True if the result is an origin fallback from a page, false otherwise.',
    )
    overall_category: Optional[str] = Field(
        None, description='The human readable speed "category" of the id.'
    )


class PagespeedApiPagespeedResponseV5(BaseModel):
    analysisUTCTimestamp: Optional[str] = Field(
        None, description='The UTC timestamp of this analysis.'
    )
    captchaResult: Optional[str] = Field(None, description='The captcha verify result')
    id: Optional[str] = Field(
        None,
        description='Canonicalized and final URL for the document, after following page redirects (if any).',
    )
    kind: Optional[str] = Field(None, description='Kind of result.')
    lighthouseResult: Optional[LighthouseResultV5] = Field(
        None, description='Lighthouse response for the audit url as an object.'
    )
    loadingExperience: Optional[PagespeedApiLoadingExperienceV5] = Field(
        None, description="Metrics of end users' page loading experience."
    )
    originLoadingExperience: Optional[PagespeedApiLoadingExperienceV5] = Field(
        None,
        description='Metrics of the aggregated page loading experience of the origin',
    )
    version: Optional[PagespeedVersion] = Field(
        None, description='The version of PageSpeed used to generate these results.'
    )
